name: Build all

on:
  workflow_dispatch:
    inputs:
      branch:
        description: PDFium branch
        required: false
        default: main
      version:
        description: PDFium version
        required: false
        default: ""
      enable_v8:
        description: Enable V8
        type: boolean
        required: false
        default: false
      is_debug:
        description: Is debug
        type: boolean
        required: false
        default: false

jobs:
  android_arm:
    name: Android ARM
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      enable_v8: ${{ github.event.inputs.enable_v8 == 'true' }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: android
      target_cpu: arm

  android_arm64:
    name: Android ARM64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      enable_v8: ${{ github.event.inputs.enable_v8 == 'true' }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: android
      target_cpu: arm64

  android_x64:
    name: Android x64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      enable_v8: ${{ github.event.inputs.enable_v8 == 'true' }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: android
      target_cpu: x64

  android_x86:
    name: Android x86
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      enable_v8: ${{ github.event.inputs.enable_v8 == 'true' }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: android
      target_cpu: x86

  ios_arm64:
    name: iOS ARM64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      enable_v8: ${{ github.event.inputs.enable_v8 == 'true' }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: ios
      target_cpu: arm64

  ios_x64:
    name: iOS x64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      enable_v8: ${{ github.event.inputs.enable_v8 == 'true' }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: ios
      target_cpu: x64

  linux_arm:
    name: Linux ARM
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      enable_v8: ${{ github.event.inputs.enable_v8 == 'true' }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: linux
      target_cpu: arm

  linux_arm64:
    name: Linux ARM64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      enable_v8: ${{ github.event.inputs.enable_v8 == 'true' }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: linux
      target_cpu: arm64

  linux_x64:
    name: Linux x64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      enable_v8: ${{ github.event.inputs.enable_v8 == 'true' }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: linux
      target_cpu: x64

  linux_x86:
    name: Linux x86
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      enable_v8: ${{ github.event.inputs.enable_v8 == 'true' }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: linux
      target_cpu: x86

  linux_musl_x64:
    name: Linux musl x64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      enable_v8: ${{ github.event.inputs.enable_v8 == 'true' }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: linux
      target_cpu: x64
      target_libc: musl

  linux_musl_x86:
    name: Linux musl x86
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      enable_v8: ${{ github.event.inputs.enable_v8 == 'true' }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: linux
      target_cpu: x86
      target_libc: musl

  mac_arm64:
    name: macOS ARM64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      enable_v8: ${{ github.event.inputs.enable_v8 == 'true' }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: mac
      target_cpu: arm64

  mac_x64:
    name: macOS x64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      enable_v8: ${{ github.event.inputs.enable_v8 == 'true' }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: mac
      target_cpu: x64

  win_arm64:
    name: Windows ARM64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      enable_v8: ${{ github.event.inputs.enable_v8 == 'true' }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: win
      target_cpu: arm64

  win_x64:
    name: Windows x64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      enable_v8: ${{ github.event.inputs.enable_v8 == 'true' }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: win
      target_cpu: x64

  win_x86:
    name: Windows x86
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      enable_v8: ${{ github.event.inputs.enable_v8 == 'true' }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: win
      target_cpu: x86

  wasm:
    name: WASM
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      enable_v8: ${{ github.event.inputs.enable_v8 == 'true' }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: wasm
      target_cpu: wasm

  mac_univ:
    name: Build macOS universal package
    runs-on: macos-latest
    needs:
      - mac_arm64
      - mac_x64
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Create universal library
        run: |
          cp -r pdfium-mac-arm64 pdfium-mac-univ
          sed -i '' '/target_cpu/d' pdfium-mac-univ/args.gn
          rm pdfium-mac-univ/lib/libpdfium.dylib
          lipo -create \
            pdfium-mac-arm64/lib/libpdfium.dylib \
            pdfium-mac-x64/lib/libpdfium.dylib \
            -output pdfium-mac-univ/lib/libpdfium.dylib
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: pdfium-mac-univ
          path: pdfium-mac-univ

  nuget:
    name: Build NuGet packages
    runs-on: windows-latest
    needs:
      - android_arm
      - android_arm64
      - android_x64
      - android_x86
      - ios_arm64
      - ios_x64
      - linux_arm
      - linux_arm64
      - linux_x64
      - linux_x86
      - linux_musl_x64
      - linux_musl_x86
      - mac_arm64
      - mac_x64
      - win_arm64
      - win_x64
      - win_x86
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: nuget
      - name: Pack
        shell: bash
        run: |
          for NUSPEC in nuget/*.nuspec; do
            echo "::group::$NUSPEC"
            nuget pack "$NUSPEC" -properties "version=${{ github.event.inputs.version || '0.0.0.0' }};branch=${GITHUB_REF#refs/heads/};commit=${GITHUB_SHA}"
            echo "::endgroup::"
          done
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: NuGet packages
          path: '*.nupkg'
      - name: Push to nuget.org
        if: env.NUGET_API_KEY && startsWith(github.event.inputs.branch, 'chromium/') && github.event.inputs.version
        run: nuget push -Source nuget.org -ApiKey $NUGET_API_KEY *.nupkg
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY  }}

  publish:
    name: Publish Release
    if: startsWith(github.event.inputs.branch, 'chromium/') && github.event.inputs.version
    runs-on: ubuntu-latest
    needs:
      - android_arm
      - android_arm64
      - android_x64
      - android_x86
      - ios_arm64
      - ios_x64
      - linux_arm
      - linux_arm64
      - linux_musl_x64
      - linux_musl_x86
      - linux_x64
      - linux_x86
      - mac_arm64
      - mac_univ
      - mac_x64
      - wasm
      - win_arm64
      - win_x64
      - win_x86
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Create tarballs
        run: |
          for DIR in pdfium-*; do
            echo "::group::$DIR"
            (cd $DIR; tar czf ../$DIR$SUFFIX.tgz *)
            echo "::endgroup::"
          done
        env:
          SUFFIX: ${{ github.event.inputs.enable_v8 == 'true' && '-v8' || '' }}${{ github.event.inputs.is_debug == 'true' && '-debug' || '' }}
      - name: Write release body
        run: echo 'This version was built with branch `${{ github.event.inputs.branch }}` of PDFium' > RELEASE.md
      - name: Get changes
        continue-on-error: true
        run: |
          CURRENT_REV=${{ github.event.inputs.branch }}
          PREVIOUS_REV=$(curl --silent "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r ".tag_name")
          git clone -b "${{ github.event.inputs.branch }}" https://pdfium.googlesource.com/pdfium.git
          cat <<END >> RELEASE.md
          ### Changes
          Commits between \`$PREVIOUS_REV\` and \`$CURRENT_REV\`:
          END
          git -C "pdfium" log origin/${PREVIOUS_REV}.. --pretty=format:'* [%s](https://pdfium.googlesource.com/pdfium/+/%H)' >> RELEASE.md
      - name: Publish Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          bodyFile: RELEASE.md
          token: ${{ secrets.GITHUB_TOKEN }}
          name: PDFium ${{ github.event.inputs.version }}
          tag: ${{ github.event.inputs.branch }}
          artifacts: "pdfium-*.tgz"
